package townframe:api-utils;

interface utils {
    use wasi:clocks/wall-clock@0.2.6.{datetime as dt};

    record errors-validation {
        issues: list<tuple<string, string>>,
    }
    record error-internal {
        message: string
    }
    type datetime = dt;
    type uuid = string;
    type json = string;

    // note: we don't include the errors since we don't want those generated
    noop: func(inc: tuple<errors-validation, error-internal, datetime, uuid>) -> result;
}

interface http-service {
    use townframe:sqlite/sqlite-connection.{connection as sqlite-connection-token};

    record service-args {
        sqlite-connections: list<tuple<string, sqlite-connection-token>>,
    }

    /// Acquire service args (capabilities) for an http-service component.
    get-args: func() -> service-args;
}
