# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
reviews:
  path_filters:
    - "**/*"
    - "!./src/daybook_compose/composeApp/src/commonMain/kotlin/org/example/daybook/uniffi/"
