repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        exclude: gh_action/dist/.*.js
      - id: check-ast
      - id: check-json
        exclude: .vscode/.*\.json
      - id: check-toml
      - id: check-yaml
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      # - id: end-of-file-fixer
      #   # exclude all generated files
      #   exclude: |
      #     (?x)^(
      #         Cargo.lock|
      #         gh_action/.*.js
      #     )$
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.36.2
    hooks:
      - id: check-dependabot
      - id: check-github-workflows
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.13.0
    hooks:
      - id: commitizen
        stages:
          - commit-msg
  - repo: local
    hooks:
      - id: deno-fmt-x
        name: Formt scripts
        language: system
        entry: deno fmt ./x/
        pass_filenames: false
      - id: deno-lint-x
        name: Lint scripts
        language: system
        entry: deno lint ./x/
        pass_filenames: false
      - id: deno-check-x
        name: Check scripts
        language: system
        entry: deno check ./x/
        pass_filenames: false
      - id: detekt-kotlin
        name: Detekt Kotlin
        language: system
        entry: ./x/gradle.ts detektMainDesktop --auto-correct --no-daemon
        pass_filenames: false
        files: \.kt$
      - id: syncpack-fmt
        name: syncpack format
        language: system
        entry: pnpm syncpack format
        pass_filenames: false
      - id: syncpack-lint
        name: syncpack lint
        language: system
        entry: pnpm syncpack lint
        pass_filenames: false
      - id: pnpm-install
        name: pnpm install
        language: system
        entry: pnpm install --frozen-lockfile
        pass_filenames: false
      - id: check-tsc
        name: check tsc
        language: system
        entry: deno run -A ./x/check-tsc.js
        pass_filenames: false
      - id: biome-fmt
        name: biome format
        language: system
        entry: pnpm format
        pass_filenames: false
      - id: biome-check
        name: biome check
        language: system
        entry: pnpm check
      - id: biome-lint
        name: biome lint
        language: system
        entry: pnpm lint
        pass_filenames: false

  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
      - id: clippy
        args:
          - "--locked"
          - "--all-features"
          - "--all-targets"
          - "--"
          - "--deny"
          - "warnings"
