package townframe:btress-api;
interface user {
    use utils.{errors-validation};
    use utils.{error-internal};
    use utils.{uuid};
    use utils.{datetime};

    record user {
        id: uuid,
        created-at: datetime,
        updated-at: datetime,
        email: option<string>,
        username: string,
    }
}
interface user-create {
    use utils.{errors-validation};
    use utils.{error-internal};
    use utils.{uuid};
    use utils.{datetime};
    use user.{user};

    /// Username occupied
    /// http error code: BAD_REQUEST
    record error-username-occupied {
        username: string,
    }

    /// Email occupied
    /// http error code: BAD_REQUEST
    record error-email-occupied {
        /// example: alice@example.com
        email: option<string>,
    }

    variant error {
        username-occupied(error-username-occupied),
        email-occupied(error-email-occupied),
        invalid-input(errors-validation),
        internal(error-internal),
    }

    record input {
        username: string,
        email: option<string>,
        password: string,
    }
    type output = user;
    call: func(inp: input) -> result<output, error>;
}
world feat-user {
    export user;
    export user-create;
}
