//! Document types module
//! 
//! This module contains the root Doc type and related types.

use crate::interlude::*;
use crate::gen::root::doc::{DocId, DocContent, DocProp};

/// Document type - manually written (excluded from generation)
/// This is the primary type with all derives (serde, uniffi, patch).
/// Use automerge types only at hydrate/reconcile boundaries.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, struct_patch::Patch)]
#[cfg_attr(feature = "uniffi", derive(uniffi::Record))]
#[patch(attribute(derive(Debug, Default)))]
#[cfg_attr(feature = "uniffi", patch(attribute(derive(uniffi::Record))))]
pub struct Doc {
    pub id: DocId,
    #[serde(with = "utils_rs::codecs::sane_iso8601")]
    pub created_at: time::OffsetDateTime,
    #[serde(with = "utils_rs::codecs::sane_iso8601")]
    pub updated_at: time::OffsetDateTime,
    pub content: DocContent,
    pub props: Vec<DocProp>,
}

// DocPatch is automatically generated by struct_patch derive macro
// It will be available as DocPatch in this module

