// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

@file:Suppress("NAME_SHADOWING")
@file:OptIn(kotlin.time.ExperimentalTime::class, kotlin.uuid.ExperimentalUuidApi::class)

package org.example.daybook.uniffi.types

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unittested etc
// in isolation, and perhaps even published as a re-useable package.
//
// However, it's important that the details of how this helper code works (e.g. the
// way that different builtin types are passed across the FFI) exactly match what's
// expected by the Rust code on the other side of the interface. In practice right
// now that means coming from the exact some version of `uniffi` that was used to
// compile the Rust component. The easiest way to ensure this is to bundle the Kotlin
// helpers directly inline like we're doing here.

import com.sun.jna.Library
import com.sun.jna.IntegerType
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import com.sun.jna.Callback
import com.sun.jna.ptr.*
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.CharBuffer
import java.nio.charset.CodingErrorAction
import java.util.concurrent.atomic.AtomicLong
import java.util.concurrent.ConcurrentHashMap
import kotlin.time.Instant
import kotlin.uuid.Uuid
import kotlinx.serialization.Serializable

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

/**
 * @suppress
 */
@Structure.FieldOrder("capacity", "len", "data")
open class RustBuffer : Structure() {
    // Note: `capacity` and `len` are actually `ULong` values, but JVM only supports signed values.
    // When dealing with these fields, make sure to call `toULong()`.
    @JvmField var capacity: Long = 0
    @JvmField var len: Long = 0
    @JvmField var data: Pointer? = null

    class ByValue: RustBuffer(), Structure.ByValue
    class ByReference: RustBuffer(), Structure.ByReference

   internal fun setValue(other: RustBuffer) {
        capacity = other.capacity
        len = other.len
        data = other.data
    }

    companion object {
        internal fun alloc(size: ULong = 0UL) = uniffiRustCall() { status ->
            // Note: need to convert the size to a `Long` value to make this work with JVM.
            UniffiLib.ffi_daybook_types_rustbuffer_alloc(size.toLong(), status)
        }.also {
            if(it.data == null) {
               throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=${size})")
           }
        }

        internal fun create(capacity: ULong, len: ULong, data: Pointer?): RustBuffer.ByValue {
            var buf = RustBuffer.ByValue()
            buf.capacity = capacity.toLong()
            buf.len = len.toLong()
            buf.data = data
            return buf
        }

        internal fun free(buf: RustBuffer.ByValue) = uniffiRustCall() { status ->
            UniffiLib.ffi_daybook_types_rustbuffer_free(buf, status)
        }
    }

    @Suppress("TooGenericExceptionThrown")
    fun asByteBuffer() =
        this.data?.getByteBuffer(0, this.len)?.also {
            it.order(ByteOrder.BIG_ENDIAN)
        }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to in the JVM, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

@Structure.FieldOrder("len", "data")
internal open class ForeignBytes : Structure() {
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : ForeignBytes(), Structure.ByValue
}
/**
 * The FfiConverter interface handles converter types to and from the FFI
 *
 * All implementing objects should be public to support external types.  When a
 * type is external we need to import it's FfiConverter.
 *
 * @suppress
 */
public interface FfiConverter<KotlinType, FfiType> {
    // Convert an FFI type to a Kotlin type
    fun lift(value: FfiType): KotlinType

    // Convert an Kotlin type to an FFI type
    fun lower(value: KotlinType): FfiType

    // Read a Kotlin type from a `ByteBuffer`
    fun read(buf: ByteBuffer): KotlinType

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    fun allocationSize(value: KotlinType): ULong

    // Write a Kotlin type to a `ByteBuffer`
    fun write(value: KotlinType, buf: ByteBuffer)

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    fun lowerIntoRustBuffer(value: KotlinType): RustBuffer.ByValue {
        val rbuf = RustBuffer.alloc(allocationSize(value))
        try {
            val bbuf = rbuf.data!!.getByteBuffer(0, rbuf.capacity).also {
                it.order(ByteOrder.BIG_ENDIAN)
            }
            write(value, bbuf)
            rbuf.writeField("len", bbuf.position().toLong())
            return rbuf
        } catch (e: Throwable) {
            RustBuffer.free(rbuf)
            throw e
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    fun liftFromRustBuffer(rbuf: RustBuffer.ByValue): KotlinType {
        val byteBuf = rbuf.asByteBuffer()!!
        try {
           val item = read(byteBuf)
           if (byteBuf.hasRemaining()) {
               throw RuntimeException("junk remaining in buffer after lifting, something is very wrong!!")
           }
           return item
        } finally {
            RustBuffer.free(rbuf)
        }
    }
}

/**
 * FfiConverter that uses `RustBuffer` as the FfiType
 *
 * @suppress
 */
public interface FfiConverterRustBuffer<KotlinType>: FfiConverter<KotlinType, RustBuffer.ByValue> {
    override fun lift(value: RustBuffer.ByValue) = liftFromRustBuffer(value)
    override fun lower(value: KotlinType) = lowerIntoRustBuffer(value)
}
// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.

internal const val UNIFFI_CALL_SUCCESS = 0.toByte()
internal const val UNIFFI_CALL_ERROR = 1.toByte()
internal const val UNIFFI_CALL_UNEXPECTED_ERROR = 2.toByte()

@Structure.FieldOrder("code", "error_buf")
internal open class UniffiRustCallStatus : Structure() {
    @JvmField var code: Byte = 0
    @JvmField var error_buf: RustBuffer.ByValue = RustBuffer.ByValue()

    class ByValue: UniffiRustCallStatus(), Structure.ByValue

    fun isSuccess(): Boolean {
        return code == UNIFFI_CALL_SUCCESS
    }

    fun isError(): Boolean {
        return code == UNIFFI_CALL_ERROR
    }

    fun isPanic(): Boolean {
        return code == UNIFFI_CALL_UNEXPECTED_ERROR
    }

    companion object {
        fun create(code: Byte, errorBuf: RustBuffer.ByValue): UniffiRustCallStatus.ByValue {
            val callStatus = UniffiRustCallStatus.ByValue()
            callStatus.code = code
            callStatus.error_buf = errorBuf
            return callStatus
        }
    }
}

class InternalException(message: String) : kotlin.Exception(message)

/**
 * Each top-level error class has a companion object that can lift the error from the call status's rust buffer
 *
 * @suppress
 */
interface UniffiRustCallStatusErrorHandler<E> {
    fun lift(error_buf: RustBuffer.ByValue): E;
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself

// Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
private inline fun <U, E: kotlin.Exception> uniffiRustCallWithError(errorHandler: UniffiRustCallStatusErrorHandler<E>, callback: (UniffiRustCallStatus) -> U): U {
    var status = UniffiRustCallStatus()
    val return_value = callback(status)
    uniffiCheckCallStatus(errorHandler, status)
    return return_value
}

// Check UniffiRustCallStatus and throw an error if the call wasn't successful
private fun<E: kotlin.Exception> uniffiCheckCallStatus(errorHandler: UniffiRustCallStatusErrorHandler<E>, status: UniffiRustCallStatus) {
    if (status.isSuccess()) {
        return
    } else if (status.isError()) {
        throw errorHandler.lift(status.error_buf)
    } else if (status.isPanic()) {
        // when the rust code sees a panic, it tries to construct a rustbuffer
        // with the message.  but if that code panics, then it just sends back
        // an empty buffer.
        if (status.error_buf.len > 0) {
            throw InternalException(FfiConverterString.lift(status.error_buf))
        } else {
            throw InternalException("Rust panic")
        }
    } else {
        throw InternalException("Unknown rust call status: $status.code")
    }
}

/**
 * UniffiRustCallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
 *
 * @suppress
 */
object UniffiNullRustCallStatusErrorHandler: UniffiRustCallStatusErrorHandler<InternalException> {
    override fun lift(error_buf: RustBuffer.ByValue): InternalException {
        RustBuffer.free(error_buf)
        return InternalException("Unexpected CALL_ERROR")
    }
}

// Call a rust function that returns a plain value
private inline fun <U> uniffiRustCall(callback: (UniffiRustCallStatus) -> U): U {
    return uniffiRustCallWithError(UniffiNullRustCallStatusErrorHandler, callback)
}

internal inline fun<T> uniffiTraitInterfaceCall(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        val err = try { e.stackTraceToString() } catch(_: Throwable) { "" }
        callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
        callStatus.error_buf = FfiConverterString.lower(err)
    }
}

internal inline fun<T, reified E: Throwable> uniffiTraitInterfaceCallWithError(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
    lowerError: (E) -> RustBuffer.ByValue
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        if (e is E) {
            callStatus.code = UNIFFI_CALL_ERROR
            callStatus.error_buf = lowerError(e)
        } else {
            val err = try { e.stackTraceToString() } catch(_: Throwable) { "" }
            callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
            callStatus.error_buf = FfiConverterString.lower(err)
        }
    }
}
// Initial value and increment amount for handles. 
// These ensure that Kotlin-generated handles always have the lowest bit set
private const val UNIFFI_HANDLEMAP_INITIAL = 1.toLong()
private const val UNIFFI_HANDLEMAP_DELTA = 2.toLong()

// Map handles to objects
//
// This is used pass an opaque 64-bit handle representing a foreign object to the Rust code.
internal class UniffiHandleMap<T: Any> {
    private val map = ConcurrentHashMap<Long, T>()
    // Start 
    private val counter = java.util.concurrent.atomic.AtomicLong(UNIFFI_HANDLEMAP_INITIAL)

    val size: Int
        get() = map.size

    // Insert a new object into the handle map and get a handle for it
    fun insert(obj: T): Long {
        val handle = counter.getAndAdd(UNIFFI_HANDLEMAP_DELTA)
        map.put(handle, obj)
        return handle
    }

    // Clone a handle, creating a new one
    fun clone(handle: Long): Long {
        val obj = map.get(handle) ?: throw InternalException("UniffiHandleMap.clone: Invalid handle")
        return insert(obj)
    }

    // Get an object from the handle map
    fun get(handle: Long): T {
        return map.get(handle) ?: throw InternalException("UniffiHandleMap.get: Invalid handle")
    }

    // Remove an entry from the handlemap and get the Kotlin object back
    fun remove(handle: Long): T {
        return map.remove(handle) ?: throw InternalException("UniffiHandleMap: Invalid handle")
    }
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
    val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
    if (libOverride != null) {
        return libOverride
    }
    return "daybook_ffi"
}

// Define FFI callback types
internal interface UniffiRustFutureContinuationCallback : com.sun.jna.Callback {
    fun callback(`data`: Long,`pollResult`: Byte,)
}
internal interface UniffiForeignFutureDroppedCallback : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceClone : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
    : Long
}
@Structure.FieldOrder("handle", "free")
internal open class UniffiForeignFutureDroppedCallbackStruct(
    @JvmField internal var `handle`: Long = 0.toLong(),
    @JvmField internal var `free`: UniffiForeignFutureDroppedCallback? = null,
) : Structure() {
    class UniffiByValue(
        `handle`: Long = 0.toLong(),
        `free`: UniffiForeignFutureDroppedCallback? = null,
    ): UniffiForeignFutureDroppedCallbackStruct(`handle`,`free`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureDroppedCallbackStruct) {
        `handle` = other.`handle`
        `free` = other.`free`
    }

}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultF32(
    @JvmField internal var `returnValue`: Float = 0.0f,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Float = 0.0f,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultF32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultF32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultF32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultF64(
    @JvmField internal var `returnValue`: Double = 0.0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Double = 0.0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultF64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultF64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultF64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultRustBuffer(
    @JvmField internal var `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultRustBuffer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultRustBuffer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteRustBuffer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultRustBuffer.UniffiByValue,)
}
@Structure.FieldOrder("callStatus")
internal open class UniffiForeignFutureResultVoid(
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultVoid(`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultVoid) {
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteVoid : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultVoid.UniffiByValue,)
}

// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.

// For large crates we prevent `MethodTooLargeException` (see #2340)
// N.B. the name of the extension is very misleading, since it is
// rather `InterfaceTooLargeException`, caused by too many methods
// in the interface for large crates.
//
// By splitting the otherwise huge interface into two parts
// * UniffiLib (this)
// * IntegrityCheckingUniffiLib
// And all checksum methods are put into `IntegrityCheckingUniffiLib`
// we allow for ~2x as many methods in the UniffiLib interface.
//
// Note: above all written when we used JNA's `loadIndirect` etc.
// We now use JNA's "direct mapping" - unclear if same considerations apply exactly.
internal object IntegrityCheckingUniffiLib {
    init {
        Native.register(IntegrityCheckingUniffiLib::class.java, findLibraryName(componentName = "daybook_types"))
        uniffiCheckContractApiVersion(this)
        uniffiCheckApiChecksums(this)
    }
    external fun ffi_daybook_types_uniffi_contract_version(
    ): Int

        
}

internal object UniffiLib {
    

    init {
        Native.register(UniffiLib::class.java, findLibraryName(componentName = "daybook_types"))
        
    }
    external fun ffi_daybook_types_rustbuffer_alloc(`size`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_daybook_types_rustbuffer_from_bytes(`bytes`: ForeignBytes.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_daybook_types_rustbuffer_free(`buf`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun ffi_daybook_types_rustbuffer_reserve(`buf`: RustBuffer.ByValue,`additional`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_daybook_types_rust_future_poll_u8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_daybook_types_rust_future_cancel_u8(`handle`: Long,
    ): Unit
    external fun ffi_daybook_types_rust_future_free_u8(`handle`: Long,
    ): Unit
    external fun ffi_daybook_types_rust_future_complete_u8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    external fun ffi_daybook_types_rust_future_poll_i8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_daybook_types_rust_future_cancel_i8(`handle`: Long,
    ): Unit
    external fun ffi_daybook_types_rust_future_free_i8(`handle`: Long,
    ): Unit
    external fun ffi_daybook_types_rust_future_complete_i8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    external fun ffi_daybook_types_rust_future_poll_u16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_daybook_types_rust_future_cancel_u16(`handle`: Long,
    ): Unit
    external fun ffi_daybook_types_rust_future_free_u16(`handle`: Long,
    ): Unit
    external fun ffi_daybook_types_rust_future_complete_u16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    external fun ffi_daybook_types_rust_future_poll_i16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_daybook_types_rust_future_cancel_i16(`handle`: Long,
    ): Unit
    external fun ffi_daybook_types_rust_future_free_i16(`handle`: Long,
    ): Unit
    external fun ffi_daybook_types_rust_future_complete_i16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    external fun ffi_daybook_types_rust_future_poll_u32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_daybook_types_rust_future_cancel_u32(`handle`: Long,
    ): Unit
    external fun ffi_daybook_types_rust_future_free_u32(`handle`: Long,
    ): Unit
    external fun ffi_daybook_types_rust_future_complete_u32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_daybook_types_rust_future_poll_i32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_daybook_types_rust_future_cancel_i32(`handle`: Long,
    ): Unit
    external fun ffi_daybook_types_rust_future_free_i32(`handle`: Long,
    ): Unit
    external fun ffi_daybook_types_rust_future_complete_i32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_daybook_types_rust_future_poll_u64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_daybook_types_rust_future_cancel_u64(`handle`: Long,
    ): Unit
    external fun ffi_daybook_types_rust_future_free_u64(`handle`: Long,
    ): Unit
    external fun ffi_daybook_types_rust_future_complete_u64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun ffi_daybook_types_rust_future_poll_i64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_daybook_types_rust_future_cancel_i64(`handle`: Long,
    ): Unit
    external fun ffi_daybook_types_rust_future_free_i64(`handle`: Long,
    ): Unit
    external fun ffi_daybook_types_rust_future_complete_i64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun ffi_daybook_types_rust_future_poll_f32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_daybook_types_rust_future_cancel_f32(`handle`: Long,
    ): Unit
    external fun ffi_daybook_types_rust_future_free_f32(`handle`: Long,
    ): Unit
    external fun ffi_daybook_types_rust_future_complete_f32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Float
    external fun ffi_daybook_types_rust_future_poll_f64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_daybook_types_rust_future_cancel_f64(`handle`: Long,
    ): Unit
    external fun ffi_daybook_types_rust_future_free_f64(`handle`: Long,
    ): Unit
    external fun ffi_daybook_types_rust_future_complete_f64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Double
    external fun ffi_daybook_types_rust_future_poll_rust_buffer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_daybook_types_rust_future_cancel_rust_buffer(`handle`: Long,
    ): Unit
    external fun ffi_daybook_types_rust_future_free_rust_buffer(`handle`: Long,
    ): Unit
    external fun ffi_daybook_types_rust_future_complete_rust_buffer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_daybook_types_rust_future_poll_void(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_daybook_types_rust_future_cancel_void(`handle`: Long,
    ): Unit
    external fun ffi_daybook_types_rust_future_free_void(`handle`: Long,
    ): Unit
    external fun ffi_daybook_types_rust_future_complete_void(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit

        
}

private fun uniffiCheckContractApiVersion(lib: IntegrityCheckingUniffiLib) {
    // Get the bindings contract version from our ComponentInterface
    val bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    val scaffolding_contract_version = lib.ffi_daybook_types_uniffi_contract_version()
    if (bindings_contract_version != scaffolding_contract_version) {
        throw RuntimeException("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    }
}
@Suppress("UNUSED_PARAMETER")
private fun uniffiCheckApiChecksums(lib: IntegrityCheckingUniffiLib) {
}

/**
 * @suppress
 */
public fun uniffiEnsureInitialized() {
    IntegrityCheckingUniffiLib
    // UniffiLib() initialized as objects are used, but we still need to explicitly
    // reference it so initialization across crates works as expected.
    UniffiLib
}

// Async support

// Public interface members begin here.


// Interface implemented by anything that can contain an object reference.
//
// Such types expose a `destroy()` method that must be called to cleanly
// dispose of the contained objects. Failure to call this method may result
// in memory leaks.
//
// The easiest way to ensure this method is called is to use the `.use`
// helper method to execute a block and destroy the object at the end.
interface Disposable {
    fun destroy()
    companion object {
        fun destroy(vararg args: Any?) {
            for (arg in args) {
                when (arg) {
                    is Disposable -> arg.destroy()
                    is ArrayList<*> -> {
                        for (idx in arg.indices) {
                            val element = arg[idx]
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Map<*, *> -> {
                        for (element in arg.values) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Iterable<*> -> {
                        for (element in arg) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                }
            }
        }
    }
}

/**
 * @suppress
 */
inline fun <T : Disposable?, R> T.use(block: (T) -> R) =
    try {
        block(this)
    } finally {
        try {
            // N.B. our implementation is on the nullable type `Disposable?`.
            this?.destroy()
        } catch (e: Throwable) {
            // swallow
        }
    }

/** 
 * Placeholder object used to signal that we're constructing an interface with a FFI handle.
 *
 * This is the first argument for interface constructors that input a raw handle. It exists is that
 * so we can avoid signature conflicts when an interface has a regular constructor than inputs a
 * Long.
 *
 * @suppress
 * */
object UniffiWithHandle

/** 
 * Used to instantiate an interface without an actual pointer, for fakes in tests, mostly.
 *
 * @suppress
 * */
object NoHandle

/**
 * @suppress
 */
public object FfiConverterUInt: FfiConverter<UInt, Int> {
    override fun lift(value: Int): UInt {
        return value.toUInt()
    }

    override fun read(buf: ByteBuffer): UInt {
        return lift(buf.getInt())
    }

    override fun lower(value: UInt): Int {
        return value.toInt()
    }

    override fun allocationSize(value: UInt) = 4UL

    override fun write(value: UInt, buf: ByteBuffer) {
        buf.putInt(value.toInt())
    }
}

/**
 * @suppress
 */
public object FfiConverterULong: FfiConverter<ULong, Long> {
    override fun lift(value: Long): ULong {
        return value.toULong()
    }

    override fun read(buf: ByteBuffer): ULong {
        return lift(buf.getLong())
    }

    override fun lower(value: ULong): Long {
        return value.toLong()
    }

    override fun allocationSize(value: ULong) = 8UL

    override fun write(value: ULong, buf: ByteBuffer) {
        buf.putLong(value.toLong())
    }
}

/**
 * @suppress
 */
public object FfiConverterLong: FfiConverter<Long, Long> {
    override fun lift(value: Long): Long {
        return value
    }

    override fun read(buf: ByteBuffer): Long {
        return buf.getLong()
    }

    override fun lower(value: Long): Long {
        return value
    }

    override fun allocationSize(value: Long) = 8UL

    override fun write(value: Long, buf: ByteBuffer) {
        buf.putLong(value)
    }
}

/**
 * @suppress
 */
public object FfiConverterFloat: FfiConverter<Float, Float> {
    override fun lift(value: Float): Float {
        return value
    }

    override fun read(buf: ByteBuffer): Float {
        return buf.getFloat()
    }

    override fun lower(value: Float): Float {
        return value
    }

    override fun allocationSize(value: Float) = 4UL

    override fun write(value: Float, buf: ByteBuffer) {
        buf.putFloat(value)
    }
}

/**
 * @suppress
 */
public object FfiConverterString: FfiConverter<String, RustBuffer.ByValue> {
    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    override fun lift(value: RustBuffer.ByValue): String {
        try {
            val byteArr = ByteArray(value.len.toInt())
            value.asByteBuffer()!!.get(byteArr)
            return byteArr.toString(Charsets.UTF_8)
        } finally {
            RustBuffer.free(value)
        }
    }

    override fun read(buf: ByteBuffer): String {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr.toString(Charsets.UTF_8)
    }

    fun toUtf8(value: String): ByteBuffer {
        // Make sure we don't have invalid UTF-16, check for lone surrogates.
        return Charsets.UTF_8.newEncoder().run {
            onMalformedInput(CodingErrorAction.REPORT)
            encode(CharBuffer.wrap(value))
        }
    }

    override fun lower(value: String): RustBuffer.ByValue {
        val byteBuf = toUtf8(value)
        // Ideally we'd pass these bytes to `ffi_bytebuffer_from_bytes`, but doing so would require us
        // to copy them into a JNA `Memory`. So we might as well directly copy them into a `RustBuffer`.
        val rbuf = RustBuffer.alloc(byteBuf.limit().toULong())
        rbuf.asByteBuffer()!!.put(byteBuf)
        return rbuf
    }

    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per UTF-16 code unit which will always be
    // enough.
    override fun allocationSize(value: String): ULong {
        val sizeForLength = 4UL
        val sizeForString = value.length.toULong() * 3UL
        return sizeForLength + sizeForString
    }

    override fun write(value: String, buf: ByteBuffer) {
        val byteBuf = toUtf8(value)
        buf.putInt(byteBuf.limit())
        buf.put(byteBuf)
    }
}

/**
 * @suppress
 */
public object FfiConverterByteArray: FfiConverterRustBuffer<ByteArray> {
    override fun read(buf: ByteBuffer): ByteArray {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr
    }
    override fun allocationSize(value: ByteArray): ULong {
        return 4UL + value.size.toULong()
    }
    override fun write(value: ByteArray, buf: ByteBuffer) {
        buf.putInt(value.size)
        buf.put(value)
    }
}



data class AddDocArgs (
    var `branchPath`: PathBuf
    , 
    var `facets`: Map<FacetKey, Json>
    , 
    var `userPath`: PathBuf?
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeAddDocArgs: FfiConverterRustBuffer<AddDocArgs> {
    override fun read(buf: ByteBuffer): AddDocArgs {
        return AddDocArgs(
            FfiConverterTypePathBuf.read(buf),
            FfiConverterMapTypeFacetKeyTypeJson.read(buf),
            FfiConverterOptionalTypePathBuf.read(buf),
        )
    }

    override fun allocationSize(value: AddDocArgs) = (
            FfiConverterTypePathBuf.allocationSize(value.`branchPath`) +
            FfiConverterMapTypeFacetKeyTypeJson.allocationSize(value.`facets`) +
            FfiConverterOptionalTypePathBuf.allocationSize(value.`userPath`)
    )

    override fun write(value: AddDocArgs, buf: ByteBuffer) {
            FfiConverterTypePathBuf.write(value.`branchPath`, buf)
            FfiConverterMapTypeFacetKeyTypeJson.write(value.`facets`, buf)
            FfiConverterOptionalTypePathBuf.write(value.`userPath`, buf)
    }
}



@Serializable
data class Blob (
    var `mime`: kotlin.String
    , 
    var `lengthOctets`: kotlin.ULong
    , 
    var `digest`: kotlin.String
    , 
    /**
     * Only to be used for small blobs
     */
    var `inline`: kotlin.ByteArray?
    , 
    var `urls`: List<kotlin.String>?
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeBlob: FfiConverterRustBuffer<Blob> {
    override fun read(buf: ByteBuffer): Blob {
        return Blob(
            FfiConverterString.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterString.read(buf),
            FfiConverterOptionalByteArray.read(buf),
            FfiConverterOptionalSequenceString.read(buf),
        )
    }

    override fun allocationSize(value: Blob) = (
            FfiConverterString.allocationSize(value.`mime`) +
            FfiConverterULong.allocationSize(value.`lengthOctets`) +
            FfiConverterString.allocationSize(value.`digest`) +
            FfiConverterOptionalByteArray.allocationSize(value.`inline`) +
            FfiConverterOptionalSequenceString.allocationSize(value.`urls`)
    )

    override fun write(value: Blob, buf: ByteBuffer) {
            FfiConverterString.write(value.`mime`, buf)
            FfiConverterULong.write(value.`lengthOctets`, buf)
            FfiConverterString.write(value.`digest`, buf)
            FfiConverterOptionalByteArray.write(value.`inline`, buf)
            FfiConverterOptionalSequenceString.write(value.`urls`, buf)
    }
}



data class Dmeta (
    var `id`: kotlin.String
    , 
    var `createdAt`: Timestamp
    , 
    var `updatedAt`: List<Timestamp>
    , 
    var `facetUuids`: Map<Uuid, FacetKey>
    , 
    var `facets`: Map<FacetKey, FacetMeta>
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeDmeta: FfiConverterRustBuffer<Dmeta> {
    override fun read(buf: ByteBuffer): Dmeta {
        return Dmeta(
            FfiConverterString.read(buf),
            FfiConverterTypeTimestamp.read(buf),
            FfiConverterSequenceTypeTimestamp.read(buf),
            FfiConverterMapTypeUuidTypeFacetKey.read(buf),
            FfiConverterMapTypeFacetKeyTypeFacetMeta.read(buf),
        )
    }

    override fun allocationSize(value: Dmeta) = (
            FfiConverterString.allocationSize(value.`id`) +
            FfiConverterTypeTimestamp.allocationSize(value.`createdAt`) +
            FfiConverterSequenceTypeTimestamp.allocationSize(value.`updatedAt`) +
            FfiConverterMapTypeUuidTypeFacetKey.allocationSize(value.`facetUuids`) +
            FfiConverterMapTypeFacetKeyTypeFacetMeta.allocationSize(value.`facets`)
    )

    override fun write(value: Dmeta, buf: ByteBuffer) {
            FfiConverterString.write(value.`id`, buf)
            FfiConverterTypeTimestamp.write(value.`createdAt`, buf)
            FfiConverterSequenceTypeTimestamp.write(value.`updatedAt`, buf)
            FfiConverterMapTypeUuidTypeFacetKey.write(value.`facetUuids`, buf)
            FfiConverterMapTypeFacetKeyTypeFacetMeta.write(value.`facets`, buf)
    }
}



data class Doc (
    var `id`: kotlin.String
    , 
    var `facets`: Map<FacetKey, Json>
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeDoc: FfiConverterRustBuffer<Doc> {
    override fun read(buf: ByteBuffer): Doc {
        return Doc(
            FfiConverterString.read(buf),
            FfiConverterMapTypeFacetKeyTypeJson.read(buf),
        )
    }

    override fun allocationSize(value: Doc) = (
            FfiConverterString.allocationSize(value.`id`) +
            FfiConverterMapTypeFacetKeyTypeJson.allocationSize(value.`facets`)
    )

    override fun write(value: Doc, buf: ByteBuffer) {
            FfiConverterString.write(value.`id`, buf)
            FfiConverterMapTypeFacetKeyTypeJson.write(value.`facets`, buf)
    }
}



data class DocAddedEvent (
    var `id`: kotlin.String
    , 
    var `heads`: List<kotlin.String>
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeDocAddedEvent: FfiConverterRustBuffer<DocAddedEvent> {
    override fun read(buf: ByteBuffer): DocAddedEvent {
        return DocAddedEvent(
            FfiConverterString.read(buf),
            FfiConverterSequenceString.read(buf),
        )
    }

    override fun allocationSize(value: DocAddedEvent) = (
            FfiConverterString.allocationSize(value.`id`) +
            FfiConverterSequenceString.allocationSize(value.`heads`)
    )

    override fun write(value: DocAddedEvent, buf: ByteBuffer) {
            FfiConverterString.write(value.`id`, buf)
            FfiConverterSequenceString.write(value.`heads`, buf)
    }
}



data class DocPatch (
    var `id`: kotlin.String
    , 
    /**
     * facets to set (insert or update)
     */
    var `facetsSet`: Map<FacetKey, Json>
    , 
    /**
     * facets to remove (by key)
     */
    var `facetsRemove`: List<FacetKey>
    , 
    /**
     * Optional user path for recording in drawer
     */
    var `userPath`: PathBuf?
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeDocPatch: FfiConverterRustBuffer<DocPatch> {
    override fun read(buf: ByteBuffer): DocPatch {
        return DocPatch(
            FfiConverterString.read(buf),
            FfiConverterMapTypeFacetKeyTypeJson.read(buf),
            FfiConverterSequenceTypeFacetKey.read(buf),
            FfiConverterOptionalTypePathBuf.read(buf),
        )
    }

    override fun allocationSize(value: DocPatch) = (
            FfiConverterString.allocationSize(value.`id`) +
            FfiConverterMapTypeFacetKeyTypeJson.allocationSize(value.`facetsSet`) +
            FfiConverterSequenceTypeFacetKey.allocationSize(value.`facetsRemove`) +
            FfiConverterOptionalTypePathBuf.allocationSize(value.`userPath`)
    )

    override fun write(value: DocPatch, buf: ByteBuffer) {
            FfiConverterString.write(value.`id`, buf)
            FfiConverterMapTypeFacetKeyTypeJson.write(value.`facetsSet`, buf)
            FfiConverterSequenceTypeFacetKey.write(value.`facetsRemove`, buf)
            FfiConverterOptionalTypePathBuf.write(value.`userPath`, buf)
    }
}



data class Embedding (
    var `facetRef`: Url
    , 
    var `refHeads`: ChangeHashSet
    , 
    var `modelTag`: kotlin.String
    , 
    /**
     * little-endian
     */
    var `vector`: kotlin.ByteArray
    , 
    var `dim`: kotlin.UInt
    , 
    var `dtype`: EmbeddingDtype
    , 
    /**
     * method tag
     */
    var `compression`: EmbeddingCompression?
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeEmbedding: FfiConverterRustBuffer<Embedding> {
    override fun read(buf: ByteBuffer): Embedding {
        return Embedding(
            FfiConverterTypeUrl.read(buf),
            FfiConverterTypeChangeHashSet.read(buf),
            FfiConverterString.read(buf),
            FfiConverterByteArray.read(buf),
            FfiConverterUInt.read(buf),
            FfiConverterTypeEmbeddingDtype.read(buf),
            FfiConverterOptionalTypeEmbeddingCompression.read(buf),
        )
    }

    override fun allocationSize(value: Embedding) = (
            FfiConverterTypeUrl.allocationSize(value.`facetRef`) +
            FfiConverterTypeChangeHashSet.allocationSize(value.`refHeads`) +
            FfiConverterString.allocationSize(value.`modelTag`) +
            FfiConverterByteArray.allocationSize(value.`vector`) +
            FfiConverterUInt.allocationSize(value.`dim`) +
            FfiConverterTypeEmbeddingDtype.allocationSize(value.`dtype`) +
            FfiConverterOptionalTypeEmbeddingCompression.allocationSize(value.`compression`)
    )

    override fun write(value: Embedding, buf: ByteBuffer) {
            FfiConverterTypeUrl.write(value.`facetRef`, buf)
            FfiConverterTypeChangeHashSet.write(value.`refHeads`, buf)
            FfiConverterString.write(value.`modelTag`, buf)
            FfiConverterByteArray.write(value.`vector`, buf)
            FfiConverterUInt.write(value.`dim`, buf)
            FfiConverterTypeEmbeddingDtype.write(value.`dtype`, buf)
            FfiConverterOptionalTypeEmbeddingCompression.write(value.`compression`, buf)
    }
}



data class FacetKey (
    var `tag`: FacetTag
    , 
    var `id`: kotlin.String
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFacetKey: FfiConverterRustBuffer<FacetKey> {
    override fun read(buf: ByteBuffer): FacetKey {
        return FacetKey(
            FfiConverterTypeFacetTag.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: FacetKey) = (
            FfiConverterTypeFacetTag.allocationSize(value.`tag`) +
            FfiConverterString.allocationSize(value.`id`)
    )

    override fun write(value: FacetKey, buf: ByteBuffer) {
            FfiConverterTypeFacetTag.write(value.`tag`, buf)
            FfiConverterString.write(value.`id`, buf)
    }
}



data class FacetMeta (
    var `createdAt`: Timestamp
    , 
    var `uuid`: List<Uuid>
    , 
    var `updatedAt`: List<Timestamp>
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFacetMeta: FfiConverterRustBuffer<FacetMeta> {
    override fun read(buf: ByteBuffer): FacetMeta {
        return FacetMeta(
            FfiConverterTypeTimestamp.read(buf),
            FfiConverterSequenceTypeUuid.read(buf),
            FfiConverterSequenceTypeTimestamp.read(buf),
        )
    }

    override fun allocationSize(value: FacetMeta) = (
            FfiConverterTypeTimestamp.allocationSize(value.`createdAt`) +
            FfiConverterSequenceTypeUuid.allocationSize(value.`uuid`) +
            FfiConverterSequenceTypeTimestamp.allocationSize(value.`updatedAt`)
    )

    override fun write(value: FacetMeta, buf: ByteBuffer) {
            FfiConverterTypeTimestamp.write(value.`createdAt`, buf)
            FfiConverterSequenceTypeUuid.write(value.`uuid`, buf)
            FfiConverterSequenceTypeTimestamp.write(value.`updatedAt`, buf)
    }
}



@Serializable
data class ImageMetadata (
    var `facetRef`: Url
    , 
    var `refHeads`: ChangeHashSet
    , 
    var `mime`: kotlin.String
    , 
    var `widthPx`: kotlin.ULong
    , 
    var `heightPx`: kotlin.ULong
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeImageMetadata: FfiConverterRustBuffer<ImageMetadata> {
    override fun read(buf: ByteBuffer): ImageMetadata {
        return ImageMetadata(
            FfiConverterTypeUrl.read(buf),
            FfiConverterTypeChangeHashSet.read(buf),
            FfiConverterString.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
        )
    }

    override fun allocationSize(value: ImageMetadata) = (
            FfiConverterTypeUrl.allocationSize(value.`facetRef`) +
            FfiConverterTypeChangeHashSet.allocationSize(value.`refHeads`) +
            FfiConverterString.allocationSize(value.`mime`) +
            FfiConverterULong.allocationSize(value.`widthPx`) +
            FfiConverterULong.allocationSize(value.`heightPx`)
    )

    override fun write(value: ImageMetadata, buf: ByteBuffer) {
            FfiConverterTypeUrl.write(value.`facetRef`, buf)
            FfiConverterTypeChangeHashSet.write(value.`refHeads`, buf)
            FfiConverterString.write(value.`mime`, buf)
            FfiConverterULong.write(value.`widthPx`, buf)
            FfiConverterULong.write(value.`heightPx`, buf)
    }
}



@Serializable
data class Note (
    var `mime`: kotlin.String
    , 
    var `content`: kotlin.String
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeNote: FfiConverterRustBuffer<Note> {
    override fun read(buf: ByteBuffer): Note {
        return Note(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: Note) = (
            FfiConverterString.allocationSize(value.`mime`) +
            FfiConverterString.allocationSize(value.`content`)
    )

    override fun write(value: Note, buf: ByteBuffer) {
            FfiConverterString.write(value.`mime`, buf)
            FfiConverterString.write(value.`content`, buf)
    }
}



data class OcrResult (
    var `facetRef`: Url
    , 
    var `refHeads`: ChangeHashSet
    , 
    var `modelTag`: kotlin.String
    , 
    var `text`: kotlin.String
    , 
    var `textRegions`: List<OcrTextRegion>?
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeOcrResult: FfiConverterRustBuffer<OcrResult> {
    override fun read(buf: ByteBuffer): OcrResult {
        return OcrResult(
            FfiConverterTypeUrl.read(buf),
            FfiConverterTypeChangeHashSet.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterOptionalSequenceTypeOcrTextRegion.read(buf),
        )
    }

    override fun allocationSize(value: OcrResult) = (
            FfiConverterTypeUrl.allocationSize(value.`facetRef`) +
            FfiConverterTypeChangeHashSet.allocationSize(value.`refHeads`) +
            FfiConverterString.allocationSize(value.`modelTag`) +
            FfiConverterString.allocationSize(value.`text`) +
            FfiConverterOptionalSequenceTypeOcrTextRegion.allocationSize(value.`textRegions`)
    )

    override fun write(value: OcrResult, buf: ByteBuffer) {
            FfiConverterTypeUrl.write(value.`facetRef`, buf)
            FfiConverterTypeChangeHashSet.write(value.`refHeads`, buf)
            FfiConverterString.write(value.`modelTag`, buf)
            FfiConverterString.write(value.`text`, buf)
            FfiConverterOptionalSequenceTypeOcrTextRegion.write(value.`textRegions`, buf)
    }
}



data class OcrTextRegion (
    /**
     * Clockwise
     */
    var `boundingBox`: List<Point>
    , 
    var `text`: kotlin.String?
    , 
    /**
     * Normalized to 0-1
     */
    var `confidenceScore`: kotlin.Float?
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeOcrTextRegion: FfiConverterRustBuffer<OcrTextRegion> {
    override fun read(buf: ByteBuffer): OcrTextRegion {
        return OcrTextRegion(
            FfiConverterSequenceTypePoint.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalFloat.read(buf),
        )
    }

    override fun allocationSize(value: OcrTextRegion) = (
            FfiConverterSequenceTypePoint.allocationSize(value.`boundingBox`) +
            FfiConverterOptionalString.allocationSize(value.`text`) +
            FfiConverterOptionalFloat.allocationSize(value.`confidenceScore`)
    )

    override fun write(value: OcrTextRegion, buf: ByteBuffer) {
            FfiConverterSequenceTypePoint.write(value.`boundingBox`, buf)
            FfiConverterOptionalString.write(value.`text`, buf)
            FfiConverterOptionalFloat.write(value.`confidenceScore`, buf)
    }
}



data class Pending (
    var `key`: FacetKey
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypePending: FfiConverterRustBuffer<Pending> {
    override fun read(buf: ByteBuffer): Pending {
        return Pending(
            FfiConverterTypeFacetKey.read(buf),
        )
    }

    override fun allocationSize(value: Pending) = (
            FfiConverterTypeFacetKey.allocationSize(value.`key`)
    )

    override fun write(value: Pending, buf: ByteBuffer) {
            FfiConverterTypeFacetKey.write(value.`key`, buf)
    }
}



data class Point (
    var `x`: kotlin.Float
    , 
    var `y`: kotlin.Float
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypePoint: FfiConverterRustBuffer<Point> {
    override fun read(buf: ByteBuffer): Point {
        return Point(
            FfiConverterFloat.read(buf),
            FfiConverterFloat.read(buf),
        )
    }

    override fun allocationSize(value: Point) = (
            FfiConverterFloat.allocationSize(value.`x`) +
            FfiConverterFloat.allocationSize(value.`y`)
    )

    override fun write(value: Point, buf: ByteBuffer) {
            FfiConverterFloat.write(value.`x`, buf)
            FfiConverterFloat.write(value.`y`, buf)
    }
}




enum class EmbeddingCompression {
    
    ZSTD;

    


    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeEmbeddingCompression: FfiConverterRustBuffer<EmbeddingCompression> {
    override fun read(buf: ByteBuffer) = try {
        EmbeddingCompression.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: EmbeddingCompression) = 4UL

    override fun write(value: EmbeddingCompression, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






enum class EmbeddingDtype {
    
    F32,
    F16,
    I8,
    BINARY;

    


    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeEmbeddingDtype: FfiConverterRustBuffer<EmbeddingDtype> {
    override fun read(buf: ByteBuffer) = try {
        EmbeddingDtype.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: EmbeddingDtype) = 4UL

    override fun write(value: EmbeddingDtype, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}





sealed class FacetTag {
    
    data class WellKnown(
        val v1: org.example.daybook.uniffi.types.WellKnownFacetTag) : FacetTag()
        
    {
        

        companion object
    }
    
    data class Any(
        val v1: kotlin.String) : FacetTag()
        
    {
        

        companion object
    }
    

    

    
    


    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFacetTag : FfiConverterRustBuffer<FacetTag>{
    override fun read(buf: ByteBuffer): FacetTag {
        return when(buf.getInt()) {
            1 -> FacetTag.WellKnown(
                FfiConverterTypeWellKnownFacetTag.read(buf),
                )
            2 -> FacetTag.Any(
                FfiConverterString.read(buf),
                )
            else -> throw RuntimeException("invalid enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: FacetTag) = when(value) {
        is FacetTag.WellKnown -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
                + FfiConverterTypeWellKnownFacetTag.allocationSize(value.v1)
            )
        }
        is FacetTag.Any -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
                + FfiConverterString.allocationSize(value.v1)
            )
        }
    }

    override fun write(value: FacetTag, buf: ByteBuffer) {
        when(value) {
            is FacetTag.WellKnown -> {
                buf.putInt(1)
                FfiConverterTypeWellKnownFacetTag.write(value.v1, buf)
                Unit
            }
            is FacetTag.Any -> {
                buf.putInt(2)
                FfiConverterString.write(value.v1, buf)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }
}





sealed class WellKnownFacet {
    
    data class Dmeta(
        val v1: org.example.daybook.uniffi.types.Dmeta) : WellKnownFacet()
        
    {
        

        companion object
    }
    
    data class RefGeneric(
        val v1: kotlin.String) : WellKnownFacet()
        
    {
        

        companion object
    }
    
    data class LabelGeneric(
        val v1: kotlin.String) : WellKnownFacet()
        
    {
        

        companion object
    }
    
    data class PseudoLabel(
        val v1: List<kotlin.String>) : WellKnownFacet()
        
    {
        

        companion object
    }
    
    data class TitleGeneric(
        val v1: kotlin.String) : WellKnownFacet()
        
    {
        

        companion object
    }
    
    data class PathGeneric(
        val v1: org.example.daybook.uniffi.types.PathBuf) : WellKnownFacet()
        
    {
        

        companion object
    }
    
    data class Pending(
        val v1: org.example.daybook.uniffi.types.Pending) : WellKnownFacet()
        
    {
        

        companion object
    }
    
    data class Note(
        val v1: org.example.daybook.uniffi.types.Note) : WellKnownFacet()
        
    {
        

        companion object
    }
    
    data class Blob(
        val v1: org.example.daybook.uniffi.types.Blob) : WellKnownFacet()
        
    {
        

        companion object
    }
    
    data class ImageMetadata(
        val v1: org.example.daybook.uniffi.types.ImageMetadata) : WellKnownFacet()
        
    {
        

        companion object
    }
    
    data class OcrResult(
        val v1: org.example.daybook.uniffi.types.OcrResult) : WellKnownFacet()
        
    {
        

        companion object
    }
    
    data class Embedding(
        val v1: org.example.daybook.uniffi.types.Embedding) : WellKnownFacet()
        
    {
        

        companion object
    }
    

    

    
    


    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeWellKnownFacet : FfiConverterRustBuffer<WellKnownFacet>{
    override fun read(buf: ByteBuffer): WellKnownFacet {
        return when(buf.getInt()) {
            1 -> WellKnownFacet.Dmeta(
                FfiConverterTypeDmeta.read(buf),
                )
            2 -> WellKnownFacet.RefGeneric(
                FfiConverterString.read(buf),
                )
            3 -> WellKnownFacet.LabelGeneric(
                FfiConverterString.read(buf),
                )
            4 -> WellKnownFacet.PseudoLabel(
                FfiConverterSequenceString.read(buf),
                )
            5 -> WellKnownFacet.TitleGeneric(
                FfiConverterString.read(buf),
                )
            6 -> WellKnownFacet.PathGeneric(
                FfiConverterTypePathBuf.read(buf),
                )
            7 -> WellKnownFacet.Pending(
                FfiConverterTypePending.read(buf),
                )
            8 -> WellKnownFacet.Note(
                FfiConverterTypeNote.read(buf),
                )
            9 -> WellKnownFacet.Blob(
                FfiConverterTypeBlob.read(buf),
                )
            10 -> WellKnownFacet.ImageMetadata(
                FfiConverterTypeImageMetadata.read(buf),
                )
            11 -> WellKnownFacet.OcrResult(
                FfiConverterTypeOcrResult.read(buf),
                )
            12 -> WellKnownFacet.Embedding(
                FfiConverterTypeEmbedding.read(buf),
                )
            else -> throw RuntimeException("invalid enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: WellKnownFacet) = when(value) {
        is WellKnownFacet.Dmeta -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
                + FfiConverterTypeDmeta.allocationSize(value.v1)
            )
        }
        is WellKnownFacet.RefGeneric -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
                + FfiConverterString.allocationSize(value.v1)
            )
        }
        is WellKnownFacet.LabelGeneric -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
                + FfiConverterString.allocationSize(value.v1)
            )
        }
        is WellKnownFacet.PseudoLabel -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
                + FfiConverterSequenceString.allocationSize(value.v1)
            )
        }
        is WellKnownFacet.TitleGeneric -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
                + FfiConverterString.allocationSize(value.v1)
            )
        }
        is WellKnownFacet.PathGeneric -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
                + FfiConverterTypePathBuf.allocationSize(value.v1)
            )
        }
        is WellKnownFacet.Pending -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
                + FfiConverterTypePending.allocationSize(value.v1)
            )
        }
        is WellKnownFacet.Note -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
                + FfiConverterTypeNote.allocationSize(value.v1)
            )
        }
        is WellKnownFacet.Blob -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
                + FfiConverterTypeBlob.allocationSize(value.v1)
            )
        }
        is WellKnownFacet.ImageMetadata -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
                + FfiConverterTypeImageMetadata.allocationSize(value.v1)
            )
        }
        is WellKnownFacet.OcrResult -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
                + FfiConverterTypeOcrResult.allocationSize(value.v1)
            )
        }
        is WellKnownFacet.Embedding -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
                + FfiConverterTypeEmbedding.allocationSize(value.v1)
            )
        }
    }

    override fun write(value: WellKnownFacet, buf: ByteBuffer) {
        when(value) {
            is WellKnownFacet.Dmeta -> {
                buf.putInt(1)
                FfiConverterTypeDmeta.write(value.v1, buf)
                Unit
            }
            is WellKnownFacet.RefGeneric -> {
                buf.putInt(2)
                FfiConverterString.write(value.v1, buf)
                Unit
            }
            is WellKnownFacet.LabelGeneric -> {
                buf.putInt(3)
                FfiConverterString.write(value.v1, buf)
                Unit
            }
            is WellKnownFacet.PseudoLabel -> {
                buf.putInt(4)
                FfiConverterSequenceString.write(value.v1, buf)
                Unit
            }
            is WellKnownFacet.TitleGeneric -> {
                buf.putInt(5)
                FfiConverterString.write(value.v1, buf)
                Unit
            }
            is WellKnownFacet.PathGeneric -> {
                buf.putInt(6)
                FfiConverterTypePathBuf.write(value.v1, buf)
                Unit
            }
            is WellKnownFacet.Pending -> {
                buf.putInt(7)
                FfiConverterTypePending.write(value.v1, buf)
                Unit
            }
            is WellKnownFacet.Note -> {
                buf.putInt(8)
                FfiConverterTypeNote.write(value.v1, buf)
                Unit
            }
            is WellKnownFacet.Blob -> {
                buf.putInt(9)
                FfiConverterTypeBlob.write(value.v1, buf)
                Unit
            }
            is WellKnownFacet.ImageMetadata -> {
                buf.putInt(10)
                FfiConverterTypeImageMetadata.write(value.v1, buf)
                Unit
            }
            is WellKnownFacet.OcrResult -> {
                buf.putInt(11)
                FfiConverterTypeOcrResult.write(value.v1, buf)
                Unit
            }
            is WellKnownFacet.Embedding -> {
                buf.putInt(12)
                FfiConverterTypeEmbedding.write(value.v1, buf)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }
}






enum class WellKnownFacetTag {
    
    DMETA,
    REF_GENERIC,
    LABEL_GENERIC,
    PSEUDO_LABEL,
    TITLE_GENERIC,
    PATH_GENERIC,
    PENDING,
    NOTE,
    BLOB,
    IMAGE_METADATA,
    OCR_RESULT,
    EMBEDDING;

    


    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeWellKnownFacetTag: FfiConverterRustBuffer<WellKnownFacetTag> {
    override fun read(buf: ByteBuffer) = try {
        WellKnownFacetTag.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: WellKnownFacetTag) = 4UL

    override fun write(value: WellKnownFacetTag, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






/**
 * @suppress
 */
public object FfiConverterOptionalFloat: FfiConverterRustBuffer<kotlin.Float?> {
    override fun read(buf: ByteBuffer): kotlin.Float? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterFloat.read(buf)
    }

    override fun allocationSize(value: kotlin.Float?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterFloat.allocationSize(value)
        }
    }

    override fun write(value: kotlin.Float?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterFloat.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalString: FfiConverterRustBuffer<kotlin.String?> {
    override fun read(buf: ByteBuffer): kotlin.String? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterString.read(buf)
    }

    override fun allocationSize(value: kotlin.String?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterString.allocationSize(value)
        }
    }

    override fun write(value: kotlin.String?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterString.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalByteArray: FfiConverterRustBuffer<kotlin.ByteArray?> {
    override fun read(buf: ByteBuffer): kotlin.ByteArray? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterByteArray.read(buf)
    }

    override fun allocationSize(value: kotlin.ByteArray?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterByteArray.allocationSize(value)
        }
    }

    override fun write(value: kotlin.ByteArray?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterByteArray.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalTypeEmbeddingCompression: FfiConverterRustBuffer<EmbeddingCompression?> {
    override fun read(buf: ByteBuffer): EmbeddingCompression? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypeEmbeddingCompression.read(buf)
    }

    override fun allocationSize(value: EmbeddingCompression?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterTypeEmbeddingCompression.allocationSize(value)
        }
    }

    override fun write(value: EmbeddingCompression?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypeEmbeddingCompression.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalSequenceString: FfiConverterRustBuffer<List<kotlin.String>?> {
    override fun read(buf: ByteBuffer): List<kotlin.String>? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterSequenceString.read(buf)
    }

    override fun allocationSize(value: List<kotlin.String>?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterSequenceString.allocationSize(value)
        }
    }

    override fun write(value: List<kotlin.String>?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterSequenceString.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalSequenceTypeOcrTextRegion: FfiConverterRustBuffer<List<OcrTextRegion>?> {
    override fun read(buf: ByteBuffer): List<OcrTextRegion>? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterSequenceTypeOcrTextRegion.read(buf)
    }

    override fun allocationSize(value: List<OcrTextRegion>?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterSequenceTypeOcrTextRegion.allocationSize(value)
        }
    }

    override fun write(value: List<OcrTextRegion>?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterSequenceTypeOcrTextRegion.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalTypePathBuf: FfiConverterRustBuffer<PathBuf?> {
    override fun read(buf: ByteBuffer): PathBuf? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypePathBuf.read(buf)
    }

    override fun allocationSize(value: PathBuf?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterTypePathBuf.allocationSize(value)
        }
    }

    override fun write(value: PathBuf?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypePathBuf.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceString: FfiConverterRustBuffer<List<kotlin.String>> {
    override fun read(buf: ByteBuffer): List<kotlin.String> {
        val len = buf.getInt()
        return List<kotlin.String>(len) {
            FfiConverterString.read(buf)
        }
    }

    override fun allocationSize(value: List<kotlin.String>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterString.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<kotlin.String>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterString.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeFacetKey: FfiConverterRustBuffer<List<FacetKey>> {
    override fun read(buf: ByteBuffer): List<FacetKey> {
        val len = buf.getInt()
        return List<FacetKey>(len) {
            FfiConverterTypeFacetKey.read(buf)
        }
    }

    override fun allocationSize(value: List<FacetKey>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeFacetKey.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<FacetKey>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeFacetKey.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeOcrTextRegion: FfiConverterRustBuffer<List<OcrTextRegion>> {
    override fun read(buf: ByteBuffer): List<OcrTextRegion> {
        val len = buf.getInt()
        return List<OcrTextRegion>(len) {
            FfiConverterTypeOcrTextRegion.read(buf)
        }
    }

    override fun allocationSize(value: List<OcrTextRegion>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeOcrTextRegion.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<OcrTextRegion>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeOcrTextRegion.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypePoint: FfiConverterRustBuffer<List<Point>> {
    override fun read(buf: ByteBuffer): List<Point> {
        val len = buf.getInt()
        return List<Point>(len) {
            FfiConverterTypePoint.read(buf)
        }
    }

    override fun allocationSize(value: List<Point>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypePoint.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<Point>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypePoint.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeTimestamp: FfiConverterRustBuffer<List<Timestamp>> {
    override fun read(buf: ByteBuffer): List<Timestamp> {
        val len = buf.getInt()
        return List<Timestamp>(len) {
            FfiConverterTypeTimestamp.read(buf)
        }
    }

    override fun allocationSize(value: List<Timestamp>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeTimestamp.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<Timestamp>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeTimestamp.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeUuid: FfiConverterRustBuffer<List<Uuid>> {
    override fun read(buf: ByteBuffer): List<Uuid> {
        val len = buf.getInt()
        return List<Uuid>(len) {
            FfiConverterTypeUuid.read(buf)
        }
    }

    override fun allocationSize(value: List<Uuid>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeUuid.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<Uuid>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeUuid.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterMapTypeFacetKeyTypeFacetMeta: FfiConverterRustBuffer<Map<FacetKey, FacetMeta>> {
    override fun read(buf: ByteBuffer): Map<FacetKey, FacetMeta> {
        val len = buf.getInt()
        return buildMap<FacetKey, FacetMeta>(len) {
            repeat(len) {
                val k = FfiConverterTypeFacetKey.read(buf)
                val v = FfiConverterTypeFacetMeta.read(buf)
                this[k] = v
            }
        }
    }

    override fun allocationSize(value: Map<FacetKey, FacetMeta>): ULong {
        val spaceForMapSize = 4UL
        val spaceForChildren = value.map { (k, v) ->
            FfiConverterTypeFacetKey.allocationSize(k) +
            FfiConverterTypeFacetMeta.allocationSize(v)
        }.sum()
        return spaceForMapSize + spaceForChildren
    }

    override fun write(value: Map<FacetKey, FacetMeta>, buf: ByteBuffer) {
        buf.putInt(value.size)
        // The parens on `(k, v)` here ensure we're calling the right method,
        // which is important for compatibility with older android devices.
        // Ref https://blog.danlew.net/2017/03/16/kotlin-puzzler-whose-line-is-it-anyways/
        value.forEach { (k, v) ->
            FfiConverterTypeFacetKey.write(k, buf)
            FfiConverterTypeFacetMeta.write(v, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterMapTypeFacetKeyTypeJson: FfiConverterRustBuffer<Map<FacetKey, Json>> {
    override fun read(buf: ByteBuffer): Map<FacetKey, Json> {
        val len = buf.getInt()
        return buildMap<FacetKey, Json>(len) {
            repeat(len) {
                val k = FfiConverterTypeFacetKey.read(buf)
                val v = FfiConverterTypeJson.read(buf)
                this[k] = v
            }
        }
    }

    override fun allocationSize(value: Map<FacetKey, Json>): ULong {
        val spaceForMapSize = 4UL
        val spaceForChildren = value.map { (k, v) ->
            FfiConverterTypeFacetKey.allocationSize(k) +
            FfiConverterTypeJson.allocationSize(v)
        }.sum()
        return spaceForMapSize + spaceForChildren
    }

    override fun write(value: Map<FacetKey, Json>, buf: ByteBuffer) {
        buf.putInt(value.size)
        // The parens on `(k, v)` here ensure we're calling the right method,
        // which is important for compatibility with older android devices.
        // Ref https://blog.danlew.net/2017/03/16/kotlin-puzzler-whose-line-is-it-anyways/
        value.forEach { (k, v) ->
            FfiConverterTypeFacetKey.write(k, buf)
            FfiConverterTypeJson.write(v, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterMapTypeUuidTypeFacetKey: FfiConverterRustBuffer<Map<Uuid, FacetKey>> {
    override fun read(buf: ByteBuffer): Map<Uuid, FacetKey> {
        val len = buf.getInt()
        return buildMap<Uuid, FacetKey>(len) {
            repeat(len) {
                val k = FfiConverterTypeUuid.read(buf)
                val v = FfiConverterTypeFacetKey.read(buf)
                this[k] = v
            }
        }
    }

    override fun allocationSize(value: Map<Uuid, FacetKey>): ULong {
        val spaceForMapSize = 4UL
        val spaceForChildren = value.map { (k, v) ->
            FfiConverterTypeUuid.allocationSize(k) +
            FfiConverterTypeFacetKey.allocationSize(v)
        }.sum()
        return spaceForMapSize + spaceForChildren
    }

    override fun write(value: Map<Uuid, FacetKey>, buf: ByteBuffer) {
        buf.putInt(value.size)
        // The parens on `(k, v)` here ensure we're calling the right method,
        // which is important for compatibility with older android devices.
        // Ref https://blog.danlew.net/2017/03/16/kotlin-puzzler-whose-line-is-it-anyways/
        value.forEach { (k, v) ->
            FfiConverterTypeUuid.write(k, buf)
            FfiConverterTypeFacetKey.write(v, buf)
        }
    }
}



/**
 * Typealias from the type name used in the UDL file to the builtin type.  This
 * is needed because the UDL type name is used in function/method signatures.
 * It's also what we have an external type that references a custom type.
 */
public typealias ChangeHashSet = List<kotlin.String>
public typealias FfiConverterTypeChangeHashSet = FfiConverterSequenceString



/**
 * Typealias from the type name used in the UDL file to the builtin type.  This
 * is needed because the UDL type name is used in function/method signatures.
 * It's also what we have an external type that references a custom type.
 */
public typealias Json = kotlin.String
public typealias FfiConverterTypeJson = FfiConverterString



/**
 * Typealias from the type name used in the UDL file to the builtin type.  This
 * is needed because the UDL type name is used in function/method signatures.
 * It's also what we have an external type that references a custom type.
 */
public typealias PathBuf = kotlin.String
public typealias FfiConverterTypePathBuf = FfiConverterString





/**
 * Typealias from the type name used in the UDL file to the custom type.  This
 * is needed because the UDL type name is used in function/method signatures.
 * It's also what we have an external type that references a custom type.
 */
public typealias Timestamp = Instant


/**
 * @suppress
 */
public object FfiConverterTypeTimestamp: FfiConverter<Timestamp, Long> {
    override fun lift(value: Long): Timestamp {
        val builtinValue = FfiConverterLong.lift(value)
        return Instant.fromEpochSeconds(builtinValue, 0)
    }

    override fun lower(value: Timestamp): Long {
        val builtinValue = value.epochSeconds
        return FfiConverterLong.lower(builtinValue)
    }

    override fun read(buf: ByteBuffer): Timestamp {
        val builtinValue = FfiConverterLong.read(buf)
        return Instant.fromEpochSeconds(builtinValue, 0)
    }

    override fun allocationSize(value: Timestamp): ULong {
        val builtinValue = value.epochSeconds
        return FfiConverterLong.allocationSize(builtinValue)
    }

    override fun write(value: Timestamp, buf: ByteBuffer) {
        val builtinValue = value.epochSeconds
        FfiConverterLong.write(builtinValue, buf)
    }
}



/**
 * Typealias from the type name used in the UDL file to the builtin type.  This
 * is needed because the UDL type name is used in function/method signatures.
 * It's also what we have an external type that references a custom type.
 */
public typealias Url = kotlin.String
public typealias FfiConverterTypeUrl = FfiConverterString





/**
 * Typealias from the type name used in the UDL file to the custom type.  This
 * is needed because the UDL type name is used in function/method signatures.
 * It's also what we have an external type that references a custom type.
 */
public typealias Uuid = Uuid


/**
 * @suppress
 */
public object FfiConverterTypeUuid: FfiConverter<Uuid, RustBuffer.ByValue> {
    override fun lift(value: RustBuffer.ByValue): Uuid {
        val builtinValue = FfiConverterByteArray.lift(value)
        return Uuid.fromByteArray(builtinValue)
    }

    override fun lower(value: Uuid): RustBuffer.ByValue {
        val builtinValue = value.toByteArray()
        return FfiConverterByteArray.lower(builtinValue)
    }

    override fun read(buf: ByteBuffer): Uuid {
        val builtinValue = FfiConverterByteArray.read(buf)
        return Uuid.fromByteArray(builtinValue)
    }

    override fun allocationSize(value: Uuid): ULong {
        val builtinValue = value.toByteArray()
        return FfiConverterByteArray.allocationSize(builtinValue)
    }

    override fun write(value: Uuid, buf: ByteBuffer) {
        val builtinValue = value.toByteArray()
        FfiConverterByteArray.write(builtinValue, buf)
    }
}
