package townframe:daybook;

interface types {
    type heads = list<string>;
}

interface drawer {
    use townframe:daybook-types/doc.{doc, doc-patch, facet-raw, doc-id};
    use types.{heads};

    variant get-doc-error {
        doc-not-found,
        invalid-heads(string),
    }
    
    variant update-doc-error {
        doc-not-found,
        branch-not-found,
        invalid-key(string),
        invalid-heads(string),
        invalid-patch(string),
    }
    
    get-doc-at-heads: func(
        doc-id: doc-id,
        heads: heads,
    ) -> result<doc, get-doc-error>;
    
    update-doc-at-heads: func(
        branch-name: string,
        heads: option<heads>,
        patch: doc-patch,
    ) -> result<_, update-doc-error>;
}

interface capabilities {
    use townframe:daybook-types/doc.{doc, doc-patch, facet-raw, doc-id};

    variant update-doc-error {
        invalid-patch(string),
        invalid-key(string),
        other(string),
    }

    resource doc-token-ro {
        get: func() -> doc;
    }

    resource doc-token-rw {
        get: func() -> doc;
        update: func(patch: doc-patch) -> result<_, update-doc-error>;
    }

    resource prop-token-ro {
        get: func() -> facet-raw;
    }

    resource prop-token-rw {
        get: func() -> facet-raw;
        update: func(patch: facet-raw) -> result<_, update-doc-error>;
    }
}

interface prop-routine {
    use townframe:daybook-types/doc.{doc-id};
    use types.{heads};
    use capabilities.{prop-token-ro, prop-token-rw};

    record prop-routine-args {
        doc-id: doc-id,
        heads: heads,
        prop-key: string,

        rw-prop-tokens: list<tuple<string, prop-token-rw>>,
        ro-prop-tokens: list<tuple<string, prop-token-ro>>,
    }

    /// Aquire args for prop-routine-args.
    /// If the running instance isn't reconginzed to be a routine,
    /// a trap is raised to the host.
    get-args: func() -> prop-routine-args;
}

interface mltools-ocr {
    use capabilities.{prop-token-ro};
    use townframe:mltools/ocr.{ocr-result};

    ocr-image: func(blob-facet: prop-token-ro) -> result<ocr-result, string>;
}

world all-guest {
    import drawer;
    import capabilities;
    import prop-routine;
    import mltools-ocr;
    import wasi:filesystem/preopens@0.2.6;
}
