package townframe:daybook-http;

world server {
    import wasi:logging/logging@0.1.0-draft;
    import wasi:clocks/monotonic-clock@0.2.6;

    import townframe:daybook-api/doc-create;
    import townframe:daybook-api/ctx;

    export wasi:http/incoming-handler@0.2.6;
}

world imports {
    import townframe:daybook-api/doc-create;
    import townframe:daybook-api/ctx;
}
