package townframe:btress-auth@0.1.0;

world btress-auth-http {
  import wasi:logging/logging@0.1.0-draft;
  import wasi:cli/environment@0.2.6;

  import townframe:api-utils/http-service;
  import townframe:sqlite/sqlite-connection;

  export wasi:http/incoming-handler@0.2.6;
}
