package townframe:daybook-api;
interface doc {
    use townframe:api-utils/utils.{errors-validation};
    use townframe:api-utils/utils.{error-internal};
    use townframe:api-utils/utils.{uuid};
    use townframe:api-utils/utils.{datetime};

    record doc {
        id: uuid,
        created-at: datetime,
        updated-at: datetime,
    }
}
interface doc-create {
    use townframe:api-utils/utils.{errors-validation};
    use townframe:api-utils/utils.{error-internal};
    use townframe:api-utils/utils.{uuid};
    use townframe:api-utils/utils.{datetime};
    use doc.{doc};

    /// Id occupied
    /// http error code: BAD_REQUEST
    record error-id-occupied {
        id: string,
    }

    variant error {
        id-occupied(error-id-occupied),
        invalid-input(errors-validation),
        internal(error-internal),
    }

    record input {
        id: uuid,
    }
    type output = doc;
    resource service {
        constructor();
        serve: func(inp: input) -> result<output, error>;
    }
}
world feat-doc {
    export doc-create;
}
