// @generated
package townframe:daybook-api;
interface doc {
    use townframe:api-utils/utils.{errors-validation};
    use townframe:api-utils/utils.{error-internal};
    use townframe:api-utils/utils.{uuid};
    use townframe:api-utils/utils.{datetime};

    type mime-type = string;

    type doc-id = string;

    record doc-image {
        mime: mime-type,
        width-px: u64,
        height-px: u64,
        blurhash: option<mutlihash>,
        blob: mutlihash,
    }

    record doc-blob {
        length-octets: u64,
        hash: doc-id,
    }

    type mutlihash = string;

    enum doc-kind {
        text,
        blob,
        image,
    }

    variant doc-content {
        text(string), 
        blob(doc-blob), 
        image(doc-image), 
    }

    enum doc-prop-kind {
        ref-generic,
        label-generic,
    }

    variant doc-prop {
        /// A link to another document.
        ref-generic(mutlihash), 
        label-generic(string), 
    }

    record doc {
        id: mutlihash,
        created-at: datetime,
        updated-at: datetime,
        content: doc-kind,
        props: list<doc-prop>,
    }
}
interface doc-create {
    use townframe:api-utils/utils.{errors-validation};
    use townframe:api-utils/utils.{error-internal};
    use townframe:api-utils/utils.{uuid};
    use townframe:api-utils/utils.{datetime};
    use doc.{mime-type};
    use doc.{doc-id};
    use doc.{doc-image};
    use doc.{doc-blob};
    use doc.{mutlihash};
    use doc.{doc-kind};
    use doc.{doc-content};
    use doc.{doc-prop-kind};
    use doc.{doc-prop};
    use doc.{doc};

    /// Id occupied
    /// http error code: BAD_REQUEST
    record error-id-occupied {
        id: string,
    }

    variant error {
        id-occupied(error-id-occupied),
        invalid-input(errors-validation),
        internal(error-internal),
    }

    record input {
        id: uuid,
    }
    type output = doc;
    resource service {
        constructor();
        serve: func(inp: input) -> result<output, error>;
    }
}
world feat-doc {
    export doc-create;
}
