// @generated
package townframe:daybook-api;

use townframe:api-utils/utils.{errors-validation};
use townframe:api-utils/utils.{error-internal};
use townframe:api-utils/utils.{uuid};
use townframe:api-utils/utils.{datetime};
use townframe:daybook-types/doc.{mime-type};
use townframe:daybook-types/doc.{doc-id};
use townframe:daybook-types/doc.{image-meta};
use townframe:daybook-types/doc.{doc-blob};
use townframe:daybook-types/doc.{multihash};
use townframe:daybook-types/doc.{doc-content-kind};
use townframe:daybook-types/doc.{doc-content};
use townframe:daybook-types/doc.{doc-prop};
use townframe:daybook-types/doc.{doc};

interface doc-create {
    use townframe:api-utils/utils.{errors-validation};
    use townframe:api-utils/utils.{error-internal};
    use townframe:api-utils/utils.{uuid};
    use townframe:api-utils/utils.{datetime};

    /// Id occupied
    /// http error code: BAD_REQUEST
    record error-id-occupied {
        id: string,
    }

    variant error {
        id-occupied(error-id-occupied),
        invalid-input(errors-validation),
        internal(error-internal),
    }

    record input {
        id: uuid,
    }
    type output = doc;
    resource service {
        constructor();
        serve: func(inp: input) -> result<output, error>;
    }
}
