package townframe:daybook-wflows;

world bundle {
    include townframe:api-utils/imports;

    import townframe:wflow/host;
    import townframe:daybook/facet-routine;
    import townframe:daybook/drawer;
    import townframe:daybook/mltools-ocr;
    import townframe:daybook/mltools-embed;
    import townframe:daybook/mltools-llm-chat;
    import townframe:daybook/index-vector;

    export townframe:wflow/bundle;
}
