package townframe:daybook-wflows;

world bundle {
    include townframe:api-utils/imports;

    import townframe:wflow/host;
    import townframe:daybook/prop-routine;
    import townframe:utils/llm-chat;

    export townframe:wflow/bundle;
}
