package townframe:am-repo;

interface repo {
    type json = string;

    type doc-id = string;

    type heads = list<string>;

    variant path-prop {
        key(string),
        index(u64),
    }

    variant obj-id {
        root,
        id(tuple<u64, list<u8>, u64>)
    }

    variant hydrate-at-head-error {
        doc-not-found,
        hash-not-found(string),
        obj-not-found,
        // corresponds to none on AmCtx::hydrate_at_head
        path-not-found,
    }

    hydrate-path-at-head: func(
        doc-id: doc-id, 
        heads: heads, 
        obj-id: obj-id, 
        path: list<path-prop>,
    ) -> result<json, hydrate-at-head-error>;
}

world guest {
    import repo;
}
