[package]
name = "pauperfuse_daybook"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[lib]
path = "lib.rs"

[dependencies]
utils_rs.workspace = true
am_utils_rs.workspace = true
daybook_core.workspace = true
daybook_types.workspace = true
pauperfuse.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
