package townframe:test-wflows;

world bundle {
    include townframe:api-utils/imports;

    import wasi:keyvalue/store@0.2.0-draft;
    import townframe:wflow/host;
    import townframe:am-repo/repo;

    export townframe:wflow/bundle;
}
