#!/usr/bin/env -S deno run --allow-all

import { $ } from "./utils.ts";

const clean = $.argv.includes("--clean");
const generateAuthTypes = $.argv.includes("--generate-auth-types");
const witConfigFiles = ["wkg.toml", "wkg.lock"];

// `wit_bindgen::generate!` copies WIT doc comments into the generated Rust
// bindings, and rustdoc treats a fenced block in a doc comment as a doctest.
// Upstream packages document examples in untyped fences —
// `wasmcloud:postgres@0.1.1-draft` ships
//
//     /// ```
//     /// SELECT email,username FROM users WHERE uuid=$1;
//     /// ```
//
// — so `cargo test --doc` tries to compile SQL as Rust and fails the build.
// Tag bare doc-comment fences as `text`, which rustdoc renders without
// compiling. This has to happen here rather than in the fetched files: `wit/deps`
// is generated by `wash wit fetch` and gitignored.
async function tagBareDocFences(depsDir: string): Promise<string[]> {
  const patched: string[] = [];
  try {
    await Deno.stat(depsDir);
  } catch {
    // A crate with no external WIT imports fetches no dependencies.
    return patched;
  }
  for await (const entry of Deno.readDir(depsDir)) {
    const path = `${depsDir}/${entry.name}`;
    if (entry.isDirectory) {
      patched.push(...await tagBareDocFences(path));
      continue;
    }
    if (!entry.name.endsWith(".wit")) continue;

    const source = await Deno.readTextFile(path);
    // Only the *opening* fence of a block may carry an info string; the closing
    // fence must stay bare or CommonMark keeps the block open. Track fence state
    // so the two are told apart.
    let inFence = false;
    let changed = false;
    const lines = source.split("\n").map((line) => {
      const fence = /^([ \t]*(?:\/\/\/|\/\/!)[ \t]*)(```)(.*)$/.exec(line);
      if (!fence) return line;
      if (inFence) {
        inFence = false;
        return line;
      }
      inFence = true;
      if (fence[3].trim() !== "") return line;
      changed = true;
      return `${fence[1]}${fence[2]}text`;
    });
    if (changed) {
      await Deno.writeTextFile(path, lines.join("\n"));
      patched.push(path);
    }
  }
  return patched;
}

const dirs: string[] = [];
for await (const entry of Deno.readDir("src")) {
  if (!entry.isDirectory) continue;

  for (const configFile of witConfigFiles) {
    try {
      await Deno.stat(`src/${entry.name}/${configFile}`);
      dirs.push(entry.name);
      break;
    } catch {
      // Try the next WIT package configuration file.
    }
  }
}
dirs.sort();

if (dirs.length === 0) {
  console.error("no wkg.toml or wkg.lock found under src/");
  Deno.exit(1);
}

for (const dir of dirs) {
  const args = clean ? ["wit", "fetch", "--clean"] : ["wit", "fetch"];
  const crateDir = $.relativeDir(`../src/${dir}/`);

  console.log(`== wash wit fetch in ${dir} ==`);
  await $`wash ${args}`.cwd(crateDir);

  for (const path of await tagBareDocFences(`src/${dir}/wit/deps`)) {
    console.log(`tagged bare doc-comment fences in ${path}`);
  }

  if (dir === "btress_auth") {
    console.log("== patch btress_auth WIT dependencies ==");
    await $`node patch-wit-deps.mjs`.cwd(crateDir);

    if (generateAuthTypes) {
      console.log("== generate btress_auth WIT types ==");
      await $`pnpm run generate:types`.cwd(crateDir);
    }
  }
}
