package townframe:daybook-types;

interface doc {
    use townframe:api-utils/utils.{datetime, json};

    type uuid = string;
    type mime-type = string;
    type multihash = string;
    type doc-id = string;
    type doc-ref = doc-id;

    record blob {
        mime: mime-type,
        length-octets: u64,
        digest: multihash,
        inline: option<list<u8>>,
        urls: option<list<string>>,
    }

    record note {
        mime: mime-type,
        content: string,
    }

    record image-metadata {
        facet-ref: string,
        ref-heads: list<string>,
        mime: mime-type,
        width-px: u64,
        height-px: u64,
    }

    record point {
        x: f32,
        y: f32,
    }

    record ocr-text-region {
        bounding-box: list<point>,
        text: option<string>,
        confidence-score: option<f32>,
    }

    record ocr-result {
        facet-ref: string,
        ref-heads: list<string>,
        model-tag: string,
        text: string,
        text-regions: option<list<ocr-text-region>>,
    }

    enum embedding-compression {
        zstd,
    }

    enum embedding-dtype {
        float32,
        float16,
        int8,
        binary,
    }

    record embedding {
        facet-ref: string,
        ref-heads: list<string>,
        model-tag: string,
        vector: list<u8>,
        dim: u32,
        dtype: embedding-dtype,
        compression: option<embedding-compression>,
    }

    record pending {
        key: string
    }

    record pseudo-label-candidate {
        label: string,
        prompts: list<string>,
        negative-prompts: list<string>,
    }

    record pseudo-label-candidates-facet {
        labels: list<pseudo-label-candidate>,
    }

    variant well-known-facet {
        ref-generic(doc-ref), 
        label-generic(string), 
        pseudo-label(list<string>), 
        title-generic(string), 
        path-generic(string), 
        image-metadata(image-metadata), 
        ocr-result(ocr-result),
        embedding(embedding),
        dmeta(dmeta),
        note(note),
        blob(blob),
        pending(pending),
        pseudo-label-candidates(pseudo-label-candidates-facet),
    }

    type facet-raw = json;

    record facet-meta {
        created-at: datetime,
        updated-at: list<datetime>,
        uuid: list<uuid>,
    }

    record dmeta {
        id: doc-id,
        created-at: datetime,
        updated-at: list<datetime>,
        facet-uuids: list<tuple<string, uuid>>,
        facets: list<tuple<string, facet-meta>>,
    }
    record doc {
        id: doc-id,
        facets: list<tuple<string, facet-raw>>,
    }

    record doc-patch {
        id: doc-id,
        facets-set: list<tuple<string, facet-raw>>,
        facets-remove: list<string>,
        user-path: option<string>,
    }

    record doc-added-event {
        id: doc-id,
        heads: list<string>,
    }
}
