package townframe:daybook-types;

interface doc {
    use townframe:api-utils/utils.{datetime, json};

    type mime-type = string;
    type multihash = string;
    type doc-id = string;
    type doc-ref = doc-id;

    record blob {
        length-octets: u64,
        hash: multihash,
    }

    enum doc-content-kind {
        text,
        blob,
    }

    variant doc-content {
        text(string), 
        blob(blob), 
    }

    record image-metadata {
        mime: mime-type,
        width-px: u64,
        height-px: u64,
    }

    record pending {
        key: string
    }

    variant well-known-prop {
        ref-generic(doc-ref), 
        label-generic(string), 
        pseudo-label(string), 
        title-generic(string), 
        path-generic(string), 
        image-metadata(image-metadata), 
        content(doc-content),
        pending(pending),
    }

    variant doc-prop {
        well-known(well-known-prop),
        any(json), // JSON string
    }

    record doc {
        id: doc-id,
        created-at: datetime,
        updated-at: datetime,
        props: list<tuple<string, doc-prop>>,
    }

    record doc-patch {
        id: doc-id,
        props-set: list<tuple<string, doc-prop>>,
        props-remove: list<string>,
    }

    record doc-added-event {
        id: doc-id,
        heads: list<string>,
    }
}
