// @generated
package townframe:daybook-types;
interface gen-doc {
    use townframe:api-utils/utils.{errors-validation};
    use townframe:api-utils/utils.{error-internal};
    use townframe:api-utils/utils.{uuid};
    use townframe:api-utils/utils.{datetime};

    type mime-type = string;

    type multihash = string;

    record doc-blob {
        length-octets: u64,
        hash: multihash,
    }

    type doc-id = string;

    enum doc-content-kind {
        text,
        blob,
    }

    variant doc-content {
        text(string), 
        blob(doc-blob), 
    }

    type doc-ref = doc-id;

    record image-meta {
        mime: mime-type,
        width-px: u64,
        height-px: u64,
    }

    variant doc-prop {
        /// A link to another document.
        ref-generic(doc-ref), 
        label-generic(string), 
        image-metadata(image-meta), 
        pseudo-label(list<string>), 
        path-generic(string), 
        title-generic(string), 
    }

    record doc {
        id: doc-id,
        created-at: datetime,
        updated-at: datetime,
        content: doc-content,
        props: list<doc-prop>,
    }

    record doc-added-event {
        id: doc-id,
        heads: list<string>,
    }
}
