[overrides]
"townframe:daybook" = { path = "../daybook_core/wit" }
"townframe:daybook-types" = { path = "../daybook_types/wit" }
"townframe:sqlite" = { path = "../wash_plugin_sqlite/wit" }
"townframe:mltools" = { path = "../mltools/wit" }
"townframe:api-utils" = { path = "../api_utils_rs/wit" }
"townframe:wflow" = { path = "../wash_plugin_wflow/wit" }
"townframe:wflow-sdk" = { path = "../wflow_sdk/wit" }
