CREATE USER zitadel;
CREATE DATABASE zitadel;
GRANT ALL PRIVILEGES ON DATABASE zitadel TO zitadel;

CREATE USER spicedb;
CREATE DATABASE spicedb;
GRANT ALL PRIVILEGES ON DATABASE spicedb TO spicedb;

CREATE USER btress;
CREATE DATABASE btress;
GRANT ALL PRIVILEGES ON DATABASE btress TO btress;

CREATE USER daybook;
CREATE DATABASE daybook;
GRANT ALL PRIVILEGES ON DATABASE daybook TO daybook;

CREATE USER granary;
CREATE DATABASE granary;
GRANT ALL PRIVILEGES ON DATABASE granary TO granary;
