package townframe:sql;

interface types {
  variant query-error {
    invalid-params(string),
    invalid-query(string),
    unexpected(string),
  }

  variant sql-value {
    null,
    integer(s64),
    real(f64),
    text(string),
    blob(list<u8>),
  }

  record result-row-entry {
    column-name: string,
    value: sql-value,
  }

  type result-row = list<result-row-entry>;
}

interface query {
  use types.{query-error, result-row, sql-value};

  query: func(query: string, params: list<sql-value>) -> result<list<result-row>, query-error>;
  query-batch: func(query: string) -> result<_, query-error>;
}

world guest {
  import types;
  import query;
}
