//! `data_model/store_pruning`: prefix pruning as a store observes it.
//!
//! The corpus states the contract from the outside. Insert the input entries into an initially
//! empty store, in order, then ask, for each input entry, whether that exact entry is in the
//! store. It never says which entries should have been removed or why, so this checks the
//! observable result rather than the mechanism, which is the property that matters: two stores
//! may prune at different moments and still have to agree on what is left.
//!
//! # What the corpus decides
//!
//! The vectors were generated by replaying these inputs through `willow25`'s in-memory store,
//! so they pin the reference implementation's semantics, and those differ from a strict reading
//! of the specification in two ways:
//!
//! - An entry that ties the new one exactly on recency is pruned when it sits under the new
//!   entry's path. The specification's `prunes` relation is strict, so it does not require
//!   this; `willow25` prunes on `is_older_than_or_equal_to`.
//! - Re-inserting the entry that is already stored is a no-op that prunes nothing, not even
//!   the entries the insert would otherwise remove. The corpus holds a vector that stores `/`,
//!   then a descendant that ties it, then `/` again, and expects the descendant to survive.
//!
//! Following the reference is deliberate rather than incidental. The vectors are the only
//! executable definition of store semantics available, the invariant a store must maintain
//! ("no two retained entries prefix-prune each other") holds either way, and the reference
//! tried strict pruning once and reverted it the same day. See ADR 010 §6.
//!
//! Both rules are pinned in the contract suite, which runs without the corpus, by
//! `an_exact_tie_prunes_the_entry_under_it` and `reinserting_a_stored_entry_prunes_nothing`.
//! The corpus is registered rather than excluded, and the two backends agree on all 866
//! vectors, which cross-validates the SQLite backend against the in-memory one.

use std::sync::Arc;

use ufotofu::codec::Decodable;
use willow25::prelude::*;

use super::{failure_report, vector_bytes, vector_names};
use crate::MemStore;
use crate::store::{InsertOutcome, WillowStore};

/// The suite these checks read.
const SUITE: &str = "data_model/store_pruning";

/// Decodes one `input` vector: a count byte, then that many concatenated absolute encodings.
async fn inputs(bytes: &[u8]) -> Vec<AuthorisedEntry> {
    let (count, encoded) = bytes
        .split_first()
        .expect("an input vector starts with a count byte");
    let mut producer = ufotofu::producer::clone_from_slice(encoded);
    let mut entries = Vec::with_capacity(usize::from(*count));
    for _ in 0..*count {
        entries.push(
            AuthorisedEntry::decode(&mut producer)
                .await
                .expect("the corpus encodes valid entries"),
        );
    }
    assert_eq!(
        producer.offset(),
        encoded.len(),
        "the input holds bytes past the entries it declares",
    );
    entries
}

/// Runs one vector against an empty `store`, returning why it disagreed with the corpus.
async fn run(store: &Arc<dyn WillowStore>, bytes: &[u8], expected: &[u8]) -> Vec<String> {
    let inputs = inputs(bytes).await;
    assert_eq!(
        expected.len(),
        inputs.len(),
        "the corpus records one output character per input entry",
    );

    let mut failed = Vec::new();

    for (index, entry) in inputs.iter().enumerate() {
        // `Outdated` is a normal outcome rather than a failure: the corpus holds entries that an
        // earlier one already prunes, and declining to store them is the store doing its job.
        match store.insert_entry(entry.clone()).await {
            Ok(InsertOutcome::Inserted { .. } | InsertOutcome::Outdated) => {}
            Err(error) => failed.push(format!("input {index}: insert failed: {error}")),
        }
    }

    for (index, entry) in inputs.iter().enumerate() {
        let stored = store
            .get_entry(entry.namespace_id(), entry.subspace_id(), entry.path())
            .await
            .expect("a read does not fail");
        // The corpus asks whether that *exact* entry is in the store, so this compares the
        // authorisation token as well: an entry that lost its place to a newer one at the same
        // path is a different value even though that path is occupied.
        let present = stored.is_some_and(|stored| &stored == entry);
        let wanted = match expected[index] {
            b't' => true,
            b'f' => false,
            other => panic!("the corpus records {other:#04x}, which is neither `t` nor `f`"),
        };
        if present != wanted {
            failed.push(format!(
                "input {index} ({}): the corpus says {}, the store has {}",
                entry.path(),
                if wanted { "present" } else { "absent" },
                if present { "present" } else { "absent" },
            ));
        }
    }

    failed
}

/// Runs every vector, each against its own store.
///
/// `stores` holds one empty store per vector, in the order of [`vector_names`]. A vector is one
/// whole scenario, so a store reused across vectors would carry entries into the next one and
/// that vector's expected output would no longer apply.
async fn every_vector(stores: Vec<Arc<dyn WillowStore>>) {
    let names = vector_names(SUITE, "input");
    assert!(!names.is_empty(), "the corpus holds no `store_pruning` vectors");
    assert_eq!(
        names,
        vector_names(SUITE, "output"),
        "every input needs an output",
    );
    assert_eq!(stores.len(), names.len(), "one empty store per vector");

    let mut failed = Vec::new();
    for (name, store) in names.iter().zip(&stores) {
        let input = vector_bytes(SUITE, "input", name);
        let output = vector_bytes(SUITE, "output", name);
        for failure in run(store, &input, &output).await {
            failed.push(format!("{name}: {failure}"));
        }
    }
    assert!(
        failed.is_empty(),
        "{}",
        failure_report("`store_pruning`", names.len(), &failed),
    );
}

#[tokio::test]
async fn mem_store_matches_every_vector() {
    let names = vector_names(SUITE, "input");
    let stores = names
        .iter()
        .map(|_| Arc::new(MemStore::new()) as Arc<dyn WillowStore>)
        .collect();
    every_vector(stores).await;
}

#[cfg(feature = "sqlite")]
#[tokio::test]
async fn sqlite_store_matches_every_vector() {
    use sqlx_utils_rs::SqlCtx;

    use crate::SqliteWillowStore;

    // One database with a scope per vector. `scope` is the storage partition, so a fresh scope
    // is a fresh empty store without paying for a fresh database per vector.
    let ctx = SqlCtx::memory()
        .await
        .expect("an ephemeral sqlite database opens");

    let names = vector_names(SUITE, "input");
    let mut stores: Vec<Arc<dyn WillowStore>> = Vec::with_capacity(names.len());
    for name in &names {
        stores.push(Arc::new(
            SqliteWillowStore::new(ctx.clone(), name.as_str())
                .await
                .expect("the store opens"),
        ));
    }

    every_vector(stores).await;
}
